# MySQL. Versions 5.0 and up are supported.

development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  hoist: localhost
  username: root
  password: 1234
  database: animotion_development

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  hoist: localhost
  username: root
  password: 1234
  database: animotion_test

production:
  adapter: mysql2
  encoding: utf8
  database: animotion_production
  password: 1234
  host: localhost
  pool: 5
  # username: mind
  # password: <%= ENV['MIND_DATABASE_PASSWORD'] %>
# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.7/en/old-client.html
#
